require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/maintenance_plans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MaintenancePlan. As you add validations to MaintenancePlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MaintenancePlan.create! valid_attributes
      get maintenance_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      maintenance_plan = MaintenancePlan.create! valid_attributes
      get maintenance_plan_url(maintenance_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_maintenance_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      maintenance_plan = MaintenancePlan.create! valid_attributes
      get edit_maintenance_plan_url(maintenance_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MaintenancePlan" do
        expect {
          post maintenance_plans_url, params: { maintenance_plan: valid_attributes }
        }.to change(MaintenancePlan, :count).by(1)
      end

      it "redirects to the created maintenance_plan" do
        post maintenance_plans_url, params: { maintenance_plan: valid_attributes }
        expect(response).to redirect_to(maintenance_plan_url(MaintenancePlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MaintenancePlan" do
        expect {
          post maintenance_plans_url, params: { maintenance_plan: invalid_attributes }
        }.to change(MaintenancePlan, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post maintenance_plans_url, params: { maintenance_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested maintenance_plan" do
        maintenance_plan = MaintenancePlan.create! valid_attributes
        patch maintenance_plan_url(maintenance_plan), params: { maintenance_plan: new_attributes }
        maintenance_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the maintenance_plan" do
        maintenance_plan = MaintenancePlan.create! valid_attributes
        patch maintenance_plan_url(maintenance_plan), params: { maintenance_plan: new_attributes }
        maintenance_plan.reload
        expect(response).to redirect_to(maintenance_plan_url(maintenance_plan))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        maintenance_plan = MaintenancePlan.create! valid_attributes
        patch maintenance_plan_url(maintenance_plan), params: { maintenance_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested maintenance_plan" do
      maintenance_plan = MaintenancePlan.create! valid_attributes
      expect {
        delete maintenance_plan_url(maintenance_plan)
      }.to change(MaintenancePlan, :count).by(-1)
    end

    it "redirects to the maintenance_plans list" do
      maintenance_plan = MaintenancePlan.create! valid_attributes
      delete maintenance_plan_url(maintenance_plan)
      expect(response).to redirect_to(maintenance_plans_url)
    end
  end
end
